version: '3.8'
services:
  web:
    build: ./web
    volumes:
      - ./web/:/app
    ports:
      - "3000:3000"#ports:
    #  - "4321:4321"  # Updated to match the port the web service is listening on
    depends_on:
      - mongo
      - nodeapi

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  nodeapi:
    build:
      context: ./api
    ports:
      - "4000:4000"  # Expose the nodeapi service on port 4000
    depends_on:
      - mongo

volumes:
  mongodata:
