version: '3.8'
services:
  web:
    build: ./web
    volumes:
      - ./web/:/app
    ports:
      - "3000:3000"
    depends_on:
      - nodeapi

  nodeapi:
    build: ./api
    ports:
      - "4000:4000"
